name: Build & Push Docker image on Tag

on:
  push:
    tags:
      - 'v*'                 # uruchamia się przy tagach np. v1.0.0
  workflow_dispatch:         # pozwala na ręczne uruchomienie z GitHub UI

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag Docker image from Git tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            IMAGE_TAG=${GITHUB_REF#refs/tags/}
          else
            IMAGE_TAG=manual-$(date +'%Y%m%d-%H%M')
          fi

          echo "Using IMAGE_TAG=$IMAGE_TAG"
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/landing-app:$IMAGE_TAG .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/landing-app:$IMAGE_TAG ${{ secrets.DOCKERHUB_USERNAME }}/landing-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/landing-app:$IMAGE_TAG
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/landing-app:latest
