name: Build & Push Docker image

on:
  push:
    tags:
      - 'v*'
    branches: [ main ]  # możesz zmienić na master lub inny branch
  workflow_dispatch: 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag Docker image from Git tag
        run: |
          IMAGE_TAG=${GITHUB_REF#refs/tags/}
          echo "Tag from GitHub: $IMAGE_TAG"
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/landing-app:$IMAGE_TAG .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/landing-app:$IMAGE_TAG ${{ secrets.DOCKERHUB_USERNAME }}/landing-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/landing-app:$IMAGE_TAG
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/landing-app:latest
