name: Build, Push, and Notify for Deployment

on:
  push:
    tags:
      - 'v*' # Triggers on tags like v1.0.0
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  build-push-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            vipinformatique/landing-app:latest
            vipinformatique/landing-app:${{ github.ref_name }}

      - name: Notify Deployment Server via Webhook
        if: steps.docker_build.outputs.digest
        run: |
          curl -X POST ${{ secrets.DEPLOYMENT_WEBHOOK_URL }} \
          -H "Content-Type: application/json" \
          -d '{"message": "New image has been pushed to Docker Hub, starting deployment."}'
